### ISSUE TITLE
support as Jupyterbook template 

### ISSUE THREAD

**Issue by jjmachan** [kai687/sphinxawesome-theme#1460]
Firstly I got to say how much I love this theme. Hands down one of the best-looking themes in the eco-system and thank you for bringing this up :)

I was wondering if support for jupyterbook would be something on your roadmap. I tried installing it but there seems to be a few small issues with some style elements.

Would love to work with you on this one with your assistance too

**Comment by jjmachan** [comment]
this can be general support for jupyter notebooks too but I feel like jupyterbook has a few handy features

**Comment by jjmachan** [comment]
Seems like little theme bugs are the main issue with jupyterbook too.  Jupyterbook is build on top of sphinx [doc](https://jupyterbook.org/en/stable/explain/sphinx.html). Only a couple of theme settings are missing.

**Comment by jjmachan** [comment]
I was able to fix most of the theming issues with using Myst with this them (you can see it in action at [docs.ragas.io](https://docs.ragas.io/en/latest/howtos/customisations/quickstart-azure-openai.html).

I'm sharing the custom CSS file I used and was wondering if we can add it to the theme too, maybe even improve it a little too. I would be more than happy to help but I don't the enough CSS to contribute.

```css
/* Base Theme */
div.cell_input {
    background: var(--background) !important;
}

.cell_output .output.text_plain,
.cell_output .output.stream {
  background: var(--background);
  border: 1px solid grey;
  border-radius: var(--mystnb-source-border-radius);
}

.cell_output .output.stderr {
  background: var(--background);
  border: 1px solid #fbc7c7;
  border-radius: var(--mystnb-source-border-radius);
}

.cell_output .output.traceback {
  background: var(--background);
  border: 1px solid #fbc7c7;
  border-radius: var(--mystnb-source-border-radius);
}

/* Pandas tables. Pulled from the Jupyter / nbsphinx CSS */
div.cell_output table {
  display: block;
  overflow-x: auto;
  white-space: nowrap;
  border: none;
  border-collapse: collapse;
  border-spacing: 0;
  color: var(--foreground);
  font-size: 1em;
  table-layout: fixed;
}

div.cell_output thead {
  border-bottom: 1px solid black;
  vertical-align: bottom;
}

div.cell_output tr,
div.cell_output th,
div.cell_output td {
  text-align: right;
  vertical-align: middle;
  padding: 0.5em 0.5em;
  line-height: normal;
  white-space: normal;
  max-width: none;
  border: none;
}

div.cell_output th {
  font-weight: bold;
}

div.cell_output tbody tr:nth-child(odd) {
  background: var(--backgound);
}

div.cell_output tbody tr:hover {
  background: rgba(66, 165, 245, 0.2);
}
```
