### ISSUE TITLE
Theme CSS not loaded on Readthedocs build; but works in local

### ISSUE THREAD

**Issue by sachin-suresh-rapyuta** [kai687/sphinxawesome-theme#1776]
The `awesome-sphinx-design.css` file does not appear to be loaded on ReadtheDocs. As a result the theme is not properly displayed on build, although it is showing on my local env. Not sure if the css loading is the issue for the page not loading as expected.

My requirements.txt file:

```
sphinx_rtd_theme>=1.2
sphinxcontrib-httpdomain
sphinxcontrib-httpexample
sphinxcontrib-mermaid==0.7.1
linuxdoc==20210324
sphinx_design
sphinxcontrib-openapi
sphinxcontrib-redoc
sphinx==6.2.1
sphinxcontrib-plantuml==0.24
sphinx_simplepdf
sphinx_disqus
sphinx-needs
sphinx-panels
sphinxawesome-theme
readthedocs-sphinx-search

```

And my theme settings is:

```

extensions = [...
'sphinx_search.extension'
]

html_static_path = ['_static']

html_css_files = ["css/custom_awesome_theme.css"]

html_theme = 'sphinxawesome_theme'

html_theme_options = {
    "logo_light": "_static/rr-logo-vertical2022-1100px-transp.png",
    "logo_dark": "_static/rr-logo-vertical2022-1100px-whitered-transp.png"
}

html_sidebars = {
  "**": ["sidebar_main_nav_links.html", "sidebar_toc.html"]
}

```

Also, the content seems to be not updated
- The caption next to the logo for example

Output in readthedocs:

![image](https://github.com/kai687/sphinxawesome-theme/assets/105263271/b933cd53-856b-41f1-a102-7ca7740dd30a)

Output in local:

![image](https://github.com/kai687/sphinxawesome-theme/assets/105263271/42c463fb-4168-4b3f-88c7-6df829508ce8)

**Comment by sachin-suresh-rapyuta** [comment]
Thanks for the reply. I did commented the two lines.

I see no difference in ReadTheDocs. As before, the fonts are totally different than in the local.

**Comment by sachin-suresh-rapyuta** [comment]
Has it got anything to do with readthedocs.yaml file? As I am extending the build commands. This is my file:

```
# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

#submodules:
#  include:
#    - paamr-deployment

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
    # You can also specify other tool versions:
    # nodejs: "16"
    # rust: "1.55"
    # golang: "1.17"
  #Upload custom simple-pdf based on language to readthedocs flyer menu
  commands:
    - pip install -r docs/requirements.txt
    - rm -rf _readthedocs/pdf
    - mkdir -p _readthedocs/pdf

    - |
      if [ "$READTHEDOCS_LANGUAGE" = "en" ]; then
        sphinx-build -b simplepdf docs _readthedocs/pdf         # Build English PDF
        find _readthedocs/pdf -type f ! -name '*.pdf' -delete   # Delete all files except .pdf
        find _readthedocs/pdf -mindepth 1 -type d -delete       # Delete all directories except .pdf
        mkdir -p _readthedocs/html/                             # Create directory for HTML
        sphinx-build -b html docs _readthedocs/html             # Build English HTML
      fi

    - |
      if [ "$READTHEDOCS_LANGUAGE" = "ja" ]; then
        sphinx-build -b simplepdf -D language='ja' -t "ja_print" docs _readthedocs/pdf  # Build Japanese PDF
        find _readthedocs/pdf -type f ! -name '*.pdf' -delete   # Delete all files except .pdf
        find _readthedocs/pdf -mindepth 1 -type d -delete       # Delete all directories except .pdf
        mkdir -p _readthedocs/html/                             # Create directory for HTML
        sphinx-build -b html -D language='ja' docs _readthedocs/html  # Build Japanese HTML
      fi


    - mv _readthedocs/pdf/*.pdf _readthedocs/pdf/$READTHEDOCS_PROJECT.pdf  # Rename and upload the PDF to readthedocs


# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# If using Sphinx, optionally build your docs in additional formats such as PDF
formats:
  - pdf

# Optionally declare the Python requirements required to build your docs
python:
  install:
    - requirements: docs/requirements.txt
```
