### ISSUE TITLE
Blockquotes not identifiable

### ISSUE THREAD

**Issue by languitar** [kai687/sphinxawesome-theme#189]
The following screenshot shows the use of a `blockquote` HTML tag:

![image](https://user-images.githubusercontent.com/1336287/97969668-adb24580-1dc0-11eb-84cb-8ef9a56ad654.png)

The list and the citation are part of the quote, the first sentence is not. This should somehow be recognizable.

**Comment by kai687** [comment]
What's the markup for this?  I didn't include any styles for blockquotes currently.

**Comment by languitar** [comment]
The section there uses this:

```rst
.. glossary::

   microservice
      A single `component` of a microservice architecture that is

         *  Highly maintainable and testable
         *  Loosely coupled
         *  Independently deployable
         *  Organized around business capabilities
         *  Owned by a small team

         -- [Microservice]_
```

Any indented paragraph becomes a blockquote.

I have currently included this as a quickfix in my custom styling:

```css
blockquote {
  background: #f9f9f9;
  border-left: 8px solid #ccc;
  margin: 1.5em 10px;
  padding: 0.5em 10px;
}
blockquote p:first-child {
  margin-top: 0;
}
blockquote p:last-child {
  margin-bottom: 0;
}
```

Maybe you can use this as a baseline.
