### ISSUE TITLE
Lacks CSS styling for contents directive

### ISSUE THREAD

**Issue by languitar** [kai687/sphinxawesome-theme#190]
Apart from sphinx's custom `toctree` directive, restructured text also provides the local `contents` directive for printing a local table of contents. Currently, the styling for this directive is missing. Especially, indentations of lower-level sections are missing.

Currently, this code

```rst
.. contents:: Overview of required steps
   :depth: 2
   :local:
```

renders this:

![image](https://user-images.githubusercontent.com/1336287/97972089-4d250780-1dc4-11eb-8046-e92a8b63deda.png)

"Use a Cookiecutter template" and "Manually set up a project" are child headings of "Boostrap the project" and should at least be indented.

**Comment by kai687** [comment]
What's the difference between using `contents` and `toctree`?

**Comment by languitar** [comment]
`contents` lists the local headings inside a single file

Here's my quickfix again:

```css
.contents.local .topic-title {
  text-transform: uppercase;
  font-size: 0.875rem;
  line-height: 1.25rem;
  --text-opacity: 1;
  color: #4a5568;
  color: rgba(74, 85, 104, var(--text-opacity));
  letter-spacing: 0.1em;
}

.contents.local li {
  padding-left: 1rem !important;
}

.contents.local ul.simple > li {
  padding-left: 0 !important;
}
```
